<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="base_length" value="0.19" />
  <xacro:property name="base_width"  value="0.19" />
  <xacro:property name="base_height" value="0.10" />
  <xacro:property name="base_mass" value="1.0" /> 

  <xacro:property name="wheel_radius" value="0.033" />
  <xacro:property name="wheel_length" value="0.02" />
  <xacro:property name="wheel_mass" value="0.3" />

 

    <!-- BASE FOOTPRINT LINK -->
  <link name="base_footprint" />

  <!-- BASE LINK -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
      <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
      <material name="blue" />
    </visual>

    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
      <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </collision>

    <!-- Approximate inertial for a solid box, mass ~ 2.0 kg -->
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
      <inertia
        ixx="${base_mass / 12.0 * (base_length*base_length + base_height*base_height)}" ixy="0.0" ixz="0.0"
        iyy="${base_mass / 12.0 * (base_height*base_height + base_width*base_width)}" iyz="0.0"
        izz="${base_mass / 12.0 * (base_width*base_width + base_length*base_length)}"/>
    </inertial>
  </link>

  <!-- WHEEL MACRO -->
  <xacro:macro name="wheel_link" params="prefix">
    <link name="${prefix}_wheel_link">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}" />
        </geometry>
        <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        <material name="grey" />
      </visual>

      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}" />
        </geometry>
        <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
      </collision>

      <!-- Approximate inertial for a wheel, mass ~ 0.1 kg -->
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <!-- Simple diagonal inertia; fine for small wheels -->
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                 iyy="0.0001" iyz="0.0"
                 izz="0.0001"/>
      </inertial>
    </link>
  </xacro:macro>

  <xacro:wheel_link prefix="right" />
  <xacro:wheel_link prefix="left" />

  <!-- CASTER WHEEL -->
  <link name="caster_wheel_link">
    <visual>
      <geometry>
        <sphere radius="${wheel_radius / 2.0}" />
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <material name="grey" />
    </visual>

    <collision>
      <geometry>
        <sphere radius="${wheel_radius / 2.0}" />
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0" />
    </collision>

    <!-- Approximate inertial for a small caster, mass ~ 0.05 kg -->
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.00005" ixy="0.0" ixz="0.0"
               iyy="0.00005" iyz="0.0"
               izz="0.00005"/>
    </inertial>
  </link>

  <!-- JOINTS -->
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link" />
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="right_wheel_link" />
    <origin xyz="${-base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
    <axis xyz="0 1 0" />
  </joint>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="left_wheel_link" />
    <origin xyz="${-base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
    <axis xyz="0 1 0" />
  </joint>

  <joint name="base_caster_wheel_joint" type="fixed">
    <parent link="base_link" />
    <child link="caster_wheel_link" />
    <origin xyz="${base_length / 3.0} 0 ${-wheel_radius / 2.0}" rpy="0 0 0" />
  </joint>

</robot>
